In [1]:
%load_ext watermark
%watermark -a 'Sebastian Raschka' -udvp torch

Sebastian Raschka 
last updated: 2019-02-15 

CPython 3.7.1
IPython 7.2.0

torch 1.0.1


In [2]:
import torch

# Some tricky things about PyTorch to keep in mind

### Changing values in a reference to an array

By default (for memory effiency), assigning a tensor to another tensor will just store a reference to that array and not make a copy:

In [3]:
a = torch.tensor([1., 2., 3.])
b = a
### sometime lates
b[0] = 99.

print(a)

tensor([99.,  2.,  3.])


If you want to treat a copy of an array seperately, you need to clone it:

In [4]:
a = torch.tensor([1., 2., 3.])
b = a.clone()
### sometime lates
b[0] = 99.

print(a)

tensor([1., 2., 3.])


### Paying attention to dimensions

Matching dimensions of matrices and vectors in linear algebra operations aside, you also have to be careful when subtracting or adding 1D to 2D arrays:

In [5]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([7., 8., 9.])

b - a

tensor([6., 6., 6.])

In [6]:
b.view(-1, 1) - a.view(-1, 1)

tensor([[6.],
        [6.],
        [6.]])

In [7]:
a.view(1, -1) - b

tensor([[-6., -6., -6.]])

In [8]:
b - a.view(-1, 1)

tensor([[6., 7., 8.],
        [5., 6., 7.],
        [4., 5., 6.]])